### ISSUE TITLE
issue with jax.check_tracer_leaks() running AR2 example

### ISSUE THREAD

**Issue by hyperfra** [pyro-ppl/numpyro#1473] opened 2022-08-27 09:27 UTC
Hi when I run the AR2.py example with jax.check_tracer_leaks() I get an error: (this happens only on my Linux machine with jax                       0.3.16  , jaxlib   0.3.15+cuda11.cudnn82    and not my laptop OSX with jaxlib 0.3.15).    

 Exception: Leaked trace MainTrace(1,DynamicJaxprTrace). Leaked tracer(s):
Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=1/0)>

here the complete log:

(numpyro) ffranco@ffranco:~/Dropbox/Work/research/sdsa/code$ /home/ffranco/anaconda3/envs/numpyro/bin/python /home/ffranco/Downloads/ar2.py
/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/contrib/control_flow/scan.py:264: FutureWarning: jax.tree_flatten is deprecated, and will be removed in a future release. Use jax.tree_util.tree_flatten instead.
  length = tree_flatten(xs)[0][0].shape[0]
Traceback (most recent call last):
  File "/home/ffranco/Downloads/ar2.py", line 138, in <module>
    main(args)
  File "/home/ffranco/Downloads/ar2.py", line 117, in main
    run_inference(model, args, rng_key, y)
  File "/home/ffranco/Downloads/ar2.py", line 96, in run_inference
    mcmc.run(rng_key, y=y)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/infer/mcmc.py", line 593, in run
    states_flat, last_state = partial_map_fn(map_args)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/infer/mcmc.py", line 386, in _single_chain_mcmc
    model_kwargs=kwargs,
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/infer/hmc.py", line 707, in init
    rng_key_init_model, model_args, model_kwargs, init_params
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/infer/hmc.py", line 659, in _init_state
    forward_mode_differentiation=self._forward_mode_differentiation,
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/infer/util.py", line 606, in initialize_model
    ) = _get_model_transforms(substituted_model, model_args, model_kwargs)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/infer/util.py", line 404, in _get_model_transforms
    model_trace = trace(model).get_trace(*model_args, **model_kwargs)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/handlers.py", line 171, in get_trace
    self(*args, **kwargs)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  File "/home/ffranco/Downloads/ar2.py", line 67, in ar2_scan
    scan(transition, init, timesteps)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/contrib/control_flow/scan.py", line 438, in scan
    msg = apply_stack(initial_msg)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/primitives.py", line 53, in apply_stack
    default_process_message(msg)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/primitives.py", line 28, in default_process_message
    msg["value"] = msg["fn"](*msg["args"], **msg["kwargs"])
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/contrib/control_flow/scan.py", line 306, in scan_wrapper
    body_fn, wrapped_carry, xs, length=length, reverse=reverse
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/jax/_src/lax/control_flow/loops.py", line 259, in scan
    init_flat, carry_avals, carry_avals_out, init_tree, *rest = _create_jaxpr(init)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/jax/_src/lax/control_flow/loops.py", line 246, in _create_jaxpr
    f, in_tree, (*carry_avals, *x_avals), "scan")
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/jax/_src/util.py", line 258, in wrapped
    return call(weak_arg, *args, **kwargs)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/jax/_src/lax/control_flow/common.py", line 58, in _initial_style_jaxpr
    fun, in_tree, in_avals, primitive_name)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/jax/_src/util.py", line 258, in wrapped
    return call(weak_arg, *args, **kwargs)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/jax/_src/lax/control_flow/common.py", line 51, in _initial_style_open_jaxpr
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals, debug)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 2094, in trace_to_jaxpr_dynamic
    del main, fun
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/jax/core.py", line 914, in new_main
    if leaked_tracers: raise leaked_tracer_error("trace", t(), leaked_tracers)
jax._src.traceback_util.UnfilteredStackTrace: Exception: Leaked trace MainTrace(1,DynamicJaxprTrace). Leaked tracer(s):

Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=1/0)>
This Tracer was created on line /home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/contrib/control_flow/scan.py:306 (scan_wrapper)

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ffranco/Downloads/ar2.py", line 138, in <module>
    main(args)
  File "/home/ffranco/Downloads/ar2.py", line 117, in main
    run_inference(model, args, rng_key, y)
  File "/home/ffranco/Downloads/ar2.py", line 96, in run_inference
    mcmc.run(rng_key, y=y)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/infer/mcmc.py", line 593, in run
    states_flat, last_state = partial_map_fn(map_args)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/infer/mcmc.py", line 386, in _single_chain_mcmc
    model_kwargs=kwargs,
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/infer/hmc.py", line 707, in init
    rng_key_init_model, model_args, model_kwargs, init_params
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/infer/hmc.py", line 659, in _init_state
    forward_mode_differentiation=self._forward_mode_differentiation,
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/infer/util.py", line 606, in initialize_model
    ) = _get_model_transforms(substituted_model, model_args, model_kwargs)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/infer/util.py", line 404, in _get_model_transforms
    model_trace = trace(model).get_trace(*model_args, **model_kwargs)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/handlers.py", line 171, in get_trace
    self(*args, **kwargs)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  File "/home/ffranco/Downloads/ar2.py", line 67, in ar2_scan
    scan(transition, init, timesteps)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/contrib/control_flow/scan.py", line 438, in scan
    msg = apply_stack(initial_msg)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/primitives.py", line 53, in apply_stack
    default_process_message(msg)
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/primitives.py", line 28, in default_process_message
    msg["value"] = msg["fn"](*msg["args"], **msg["kwargs"])
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/contrib/control_flow/scan.py", line 306, in scan_wrapper
    body_fn, wrapped_carry, xs, length=length, reverse=reverse
  File "/home/ffranco/anaconda3/envs/numpyro/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
Exception: Leaked trace MainTrace(1,DynamicJaxprTrace). Leaked tracer(s):

Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=1/0)>
This Tracer was created on line /home/ffranco/anaconda3/envs/numpyro/lib/python3.7/site-packages/numpyro/contrib/control_flow/scan.py:306 (scan_wrapper)

**Comment by fehiepsi** [comment] 2022-08-27 15:36
Looking like you are using the released version. The issue is fixed in the dev branch. The tree flatten warning is also fixed in the dev branch. You can install dev version using the instruction in Readme file.

**Comment by fehiepsi** [comment] 2022-09-06 01:15
We just made a new release. Pls reopen the topic if you still get the issue.

**Closed by fehiepsi** 2022-09-06 01:15 UTC
Labels: question

**Comment by hyperfra** [comment] 2022-09-06 06:39
With dev version the issue was solved. Will try with new version but will probably work


Sent from my iPhone

On 6 Sep 2022, at 02:16, Du Phan ***@***.***> wrote:

﻿

We just made a new release. Pls reopen the topic if you still get the issue.
