### ISSUE TITLE
GPU version install

### ISSUE THREAD

**Issue by ross-h1** [pyro-ppl/numpyro#505] opened 2019-12-29 06:44 UTC
Hi,  Firstly thanks for an excellent piece of work, am seeing huge speedups in inference v. other frameworks, making a big impact on my research!

Please excuse potentially naiive question, but I'm struggling to see how to install / run a GPU capable Numpyro. I have JAX working on GPU... some pointers please?! 

Thank you

Ross

**Comment by fehiepsi** [comment] 2019-12-29 14:23
Hi Ross, I think that you want to call [numpyro.set_platform('gpu')](http://num.pyro.ai/en/stable/utilities.html#set-platform) at the top of your program.

**Comment by ross-h1** [comment] 2019-12-29 17:45
Thank you, have tried that, but i seem to have an install issue. I can set up a working JAX environment (CPU/GPU) as per the JAX install guide. 

If i then install Numpyro running either:
pip install git+https://github.com/pyro-ppl/numpyro.git
or 
pip install numpyro

This breaks this install, for both numpyro with the command you mention, or with any JAX code set up to use GPU, and I get the following error:

 File "/home/..../anaconda3/envs/PYRO/lib/python3.7/site-packages/jaxlib/xla_client.py", line 248, in get_local_backend
    raise RuntimeError('Unknown backend {}'.format(name))

the pip installer seems to uninstall jax/jaxlib and replace them with older versions...

**Comment by fehiepsi** [comment] 2019-12-29 18:37
@ross-h1 Currently, NumPyro only works with jax==0.1.53 and jaxlib==0.1.36. If you want to use the latest jax/jaxlib version then you might want to install the PR https://github.com/pyro-ppl/numpyro/pull/496. There is an issue in the last version of jax that will break some NumPyro models so we can’t merge that PR yet.

FYI, you can use pip with no-deps flag to not update dependencies https://pip.pypa.io/en/stable/reference/pip_install/#install-no-deps. But I would recommend to install jaxlib==0.1.36 instead.

**Comment by neerajprad** [comment] 2019-12-30 19:21
@ross-h1 - I am closing this issue, but please feel free to reopen if you continue to face issues. The simplest way would be to follow @fehiepsi's suggestion and install a `jaxlib==0.1.36` using installation instructions for the [GPU](https://github.com/google/jax#pip-installation).

**Closed** 2019-12-30 19:21 UTC

**Comment by benwaldner** [comment] 2020-08-24 00:10
I had the same issue with Jax and Jaxlib. Didnt found any way how to solve it. Anyone solved it? I dont know what to try else. All things suggested come up with the error: Backend GPU not found. And I tried it on several machines/ linux-installations. Even on CPU the problem is that it doesnt use all the cores on 100% but skip after one CPU-core hits 100% and doesnt load balancing it efficiently on the other cores. Making it enormously slow.

Anyone found something that worked to solve this error?
I really dont know what to try else.

**Comment by fehiepsi** [comment] 2020-08-24 02:34
@benwaldner Did you follow the steps in [jax](https://github.com/google/jax#pip-installation) for GPU support? Make sure that you specify the correct CUDA_VERSION in your system.

**Comment by ashleymaeconard** [comment] 2021-11-03 23:29
I am also seeing the same error and issue. I installed jax with Conda using `conda install -c conda-forge jax` which installs `0.2.17`. So, would you recommend somehow removing jax within Conda, and then following the `pip` installation instructions for the GPU?

**Comment by fehiepsi** [comment] 2021-11-04 04:08
That's right. Currently, we can't install jax with gpu support using conda.

**Comment by benwaldner** [comment] 2021-11-05 22:18
> I am also seeing the same error and issue. I installed jax with Conda using `conda install -c conda-forge jax` which installs `0.2.17`. So, would you recommend somehow removing jax within Conda, and then following the `pip` installation instructions for the GPU?

Hi, Ashley, did it worked for you? I skiped my codes after not be able to fix it back than. But if you could make it. I will check my codes again and try to fix it the same way as you did.

TIA.
