### ISSUE TITLE
Error in trying to run Example: MCMC Methods for Tall Data

### ISSUE THREAD

**Issue by srijaniiserprinceton** [pyro-ppl/numpyro#1032] opened 2021-05-07 15:11 UTC
I try to run the code in 

http://num.pyro.ai/en/stable/examples/covtype.html?highlight=GPU#sphx-glr-download-examples-covtype-py

TypeError: Argument 'None' of type '<class 'NoneType'>' is not a valid JAX type

**Comment by fehiepsi** [comment] 2021-05-08 03:15
@srijaniiserprinceton Could you let me know which commands that you used to trigger that error? I can't reproduce it in my system. You might consider updating your `jax/jaxlib` versions together with using master branch: `pip install git+https://github.com/pyro-ppl/numpyro`

**Comment by fehiepsi** [comment] 2021-05-13 03:28
I think this issue is due to using an old version of jax/jaxlib. Please feel free to open this issue again if that's not the case.

**Comment by pforero** [comment] 2021-05-14 11:12
Hi!

I've had the same error running the example in Bayesian Regression Using Numpyro when I run the first "mcmc.run".

Numpyro: 0.6.0
jax: 0.2.13
jaxlib: 0.1.66

Hope it helps.

**Comment by fehiepsi** [comment] 2021-05-14 14:31
@pforero Could you help me try to run with master version:
```
pip install git+https://github.com/pyro-ppl/numpyro.git
```
I can't reproduce the error in my system. We also have a test for this example so it can run on CI (with the latest jax/jaxlib versions).

**Comment by pforero** [comment] 2021-05-17 10:44
Hi @fehiepsi, I have tried pip installing the master version in my environment, and had the same error.

I have tried some "bad" debugging (bad because I am not familiar enough with Jax or numpyro to know what the appropriate behaviour is).

What I have found is that in the firs run of the model the X values are a DeviceArray, an work fine. But the second iteration the X values are a ConcreteArray, and the sample becomes a "None" object.

Looking into Jax it seems to be the error due to the initial state just being a "None" instead of some values. Like I said, don't know the correct behaviour. So don't know if this information is useful, or it is just its correct behaviour.

Anything else that you need just say so.

**Comment by fehiepsi** [comment] 2021-05-20 04:33
@pforero Could you try to run `pip uninstall jax jaxlib` 2 times, then install again? I just checked the tutorial in colab and couldn't observe the error. Could you help me:
+ print jax/jaxlib versions in the notebook
+ run the tutorial
+ copy the notebook with error message to gist

Thanks!

**Comment by openerror** [comment] 2021-05-21 03:37
I ran into the same error message when trying the 8 schools example as well. I installed `numpyro` through conda-forge after seeing the relevant commit.

- `jax` 0.2.13
- `jaxlib` 0.1.67
- `numpyro` 0.6.0

When I restarted with a fresh virtual environment and installed `numpyro` directly from pip, the error went away. But then I am "stuck" with an older version of jax (0.2.10).

**Comment by fehiepsi** [comment] 2021-05-21 03:40
@openerror Could you try to install numpyro with `pip install git+https://github.com/pyro-ppl/numpyro.git`? The next version of numpyro will relax that jax/jaxlib versioning restriction.

**Comment by openerror** [comment] 2021-05-21 07:47
> @openerror Could you try to install numpyro with `pip install git+https://github.com/pyro-ppl/numpyro.git`? The next version of numpyro will relax that jax/jaxlib versioning restriction.

As you suggested, I installed numpyro from github, and now the 8 schools example is working well.

**Comment by fehiepsi** [comment] 2021-05-27 22:11
It seems that the issue has happened with the last release and has been resolved in numpyro master. Please feel free to reopen this issue if the problem still happens.

**Closed by fehiepsi** 2021-05-27 22:11 UTC
Labels: question
