### ISSUE TITLE
Uniform distribution

### ISSUE THREAD

**Issue by jodablei** [pyro-ppl/numpyro#404] opened 2019-10-18 18:07 UTC
Hi,

I've been using some of the distributions that are implemented in numpyro, one being the Uniform distribution. Turns out that when evaluating the log_prob of a point outside the support, the returned value is not -inf. Is this intended behavior? I've only noticed this because I was getting posterior samples using MCMC that according to my priors shouldn't be possible.

```
from numpyro.distributions import Uniform
pu = Uniform(0.5, 1.) 
pu.log_prob(2.) == pu.log_prob(0.7) 
```

Thanks in advance

**Comment by neerajprad** [comment] 2019-10-18 18:13
If you are using the master branch of numpyro, you can use `numpyro.enable_validation()` to do distribution args checking. In this case, it will throw a warning and return `-inf` as you expect. If you are using the release version you can use `Distribution._validate_args = True` which will throw an exception for all such cases. This isn't enabled by default, because args checking on large arrays can be expensive, so it makes sense to only turn this flag on during model development. 

This should serve as a reminder for us to use this flag in all tutorials / examples for the next release.

**Comment by fehiepsi** [comment] 2019-10-18 18:16
> posterior samples using MCMC that according to my priors shouldn't be possible

This is unexpected behavior, which indicates some problems with how we handle the priors' supports. Could you provide us a reproducible code? Thanks!

**Comment by jodablei** [comment] 2019-10-18 18:22
The sampler I am currently using is not from numpyro. For now, I am only importing some of the distributions from numpyro and I use the base class to create new ones. Do the numpyro samplers perform a support check before evaluating the probability? If so, I guess I could look at the code and do something similar.

**Comment by fehiepsi** [comment] 2019-10-18 18:36
If you use a different sampler, then using `numpyro.enable_validation()` should give the expected behavior for you. In NumPyro, we [transform latent values to unconstrained space](https://github.com/pyro-ppl/numpyro/blob/master/numpyro/infer/util.py#L369) and run MCMC in unconstrained space. After we collected all unconstrained samples, we transform them back to the prior support domain.

**Comment by fehiepsi** [comment] 2019-10-19 14:27
> The sampler I am currently using is not from numpyro

If you are using NumPyro, it might be helpful to make your sampler a subclass of [MCMCKernel](https://github.com/pyro-ppl/numpyro/blob/master/numpyro/infer/mcmc.py#L456). Then you can use [MCMC](https://github.com/pyro-ppl/numpyro/blob/master/numpyro/infer/mcmc.py#L678) interface to get samples (without having to play with chain stuff: sequential/parallel/vectorized). If so, please let us know if you observe some limitations of the current interface.

> use the base class to create new ones

Do you want to make PRs for those ones? ;)

**Comment by fehiepsi** [comment] 2019-10-24 02:42
@jodablei I close this issue because I think that `numpyro.enable_validation()` will do what you need. Feel free to reopen this issue if the issue still happens in your code!

**Closed by fehiepsi** 2019-10-24 02:42 UTC
