### ISSUE TITLE
Trying to reproduce the textmessage-example from bayesian-methods-for-hackers

### ISSUE THREAD

**Issue by timnon** [pyro-ppl/numpyro#351] opened 2019-09-25 07:58 UTC
I had some problems recreating the textmessage-example from bayesian methods for hackers (https://nbviewer.jupyter.org/github/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/blob/master/Chapter1_Introduction/Ch1_Introduction_PyMC2.ipynb).

This example requires a `DiscreteUniform`-distribution, which can be created via a `Categorical`. However, the following model stalled when sampling from the posterior:

```
import numpyro
import numpyro.distributions as dist
from numpyro.mcmc import MCMC, NUTS
import jax
import numpy as np

n_count_data = 10

def model():
    tau_ = numpyro.sample("tau_", dist.Categorical(np.repeat(1./n_count_data, n_count_data)), obs=np.arange(n_count_data))

key = jax.random.PRNGKey(0)
key, key_ = jax.random.split(key)
num_warmup, num_samples = 100, 1000

kernel = NUTS(model)
mcmc = MCMC(kernel, num_warmup, num_samples)
mcmc.run(key_)
mcmc.print_summary()
```

I would expect this to terminate.

**Comment by fehiepsi** [comment] 2019-09-25 13:03
Hi @timnon, the issue is your model does not have any latent variable for MCMC to run over. Your `tau_` is an observed variable. You can take a look at this [gist](https://nbviewer.jupyter.org/gist/fehiepsi/aa6ad7ff128ba57ffc46ca1101bb35fc) to see how to make a corresponding model in NumPyro.

**Comment by fehiepsi** [comment] 2019-09-26 04:47
@timnon Thanks for raising this issue. I am going to close this issue because the site effect that MCMC stuck when the model has no latent site has been addressed in #352. For a repro code of the textmessage example, you can take a look at the gist in the above comment. :)

**Closed by fehiepsi** 2019-09-26 04:47 UTC

**Comment by timnon** [comment] 2019-10-05 11:06
Thanks for the feedback, would be indeed good to have some error message in case there is no variable to sample from. Also thanks for the gist, looks more sane than my attempt. In general, is there already some attempt to adapt bayesian-methods-for-hackers to numpyro? Or is it too early due to changing interfaces, e.g. missing `DiscreteUniform`, but which can be easily created like in the gist.

**Comment by fehiepsi** [comment] 2019-10-05 13:29
Hi @timnon, AFAIK there is no attempt to adapt bayesian methods for hackers to numpyro. I don't think that there will be any blocker for it. The current API will be stable. For the next release, we'll only replace `from numpyro.mcmc import NUTS, MCMC` to `from numpyro.infer import NUTS, MCMC`.

Do you plan to try it? That's would be a great addition to NumPyro ecosystem. We are happy to help for any problem which you meet during the translation! FYI, I summarize some differences (beside DiscreteUniform) between NumPyro and PyMC3, which will be helpful for the translation:
+ `mean = pm.Deterministic("mean", alpha + beta*X)` is translated to
```
mean = alpha + beta * X
numpyro.sample("mean", dist.Delta(mean), obs=mean)
```
+ `pm.Potential("error", logp)` is translated to
```
dist.Delta("error", log_density=logp, obs=0.)
```
+ We don't have Wishart distribution implemented (useful for Chapter 6). But it can be relaced by `LKJ` or `LKJCholesky`, which are more stable (according Stan reference manual).
+ For setting starting values, `mu = pm.Uniform( "mu", 0, 100, testval=data.mean())` will be replaced by (which I plan to make a PR for this today)
```
kernel = NUTS(model, init_strategy=init_to_values({"mu": data.mean()}))
```
+ Currently, we don't support the model with discrete latent variable `pm.Categorical` in Chapter 3. But we will support it in the future (Pyro has support for such models). Until then I guess we can use Uniform prior similar to the way we convert a discrete variable with `DiscreteUniform` prior to a continuous variable with `Uniform` prior (I just guess without trying):
```
p1 = pm.Uniform('p', 0, 1)
p2 = 1 - p1
p = T.stack([p1, p2])
assignment = pm.Categorical("assignment", p, shape=data.shape[0])
```
will be translated to
```
p1 = numpyro.sample("p", dist.Uniform(0, 1))
u = numpyro.sample("u", dist.Uniform(0, 1), sample_shape=(data.shape[0],))
assignment = u > p1
```
