### ISSUE TITLE
Anaconda build broken?

### ISSUE THREAD

**Issue by justinrporter** [pyro-ppl/numpyro#1354] opened 2022-03-06 16:20 UTC
I think the anaconda distribution is broken at the moment.

With a fresh install of numpyro from conda-forge, running `python -c 'import numpyro'` I get:

```
[libprotobuf ERROR google/protobuf/descriptor_database.cc:641] File already exists in database: tensorflow/compiler/xla/xla_data.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:2021] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
Aborted
```

This looks like possibly a consequence of [this issue](https://github.com/google/jax/issues/9643), which I think is maybe fixed now... unclear if the numpyro anaconda distribution needs to do anything about this?

**Comment by fehiepsi** [comment] 2022-03-06 18:16
Hi @justinrporter, I just merged https://github.com/conda-forge/numpyro-feedstock/pull/9. Could you double check if the issue is resolved. The tests passed there.

**Comment by justinrporter** [comment] 2022-03-06 18:46
No good...

conda list shows: `numpyro                   0.9.0              pyhd8ed1ab_0    conda-forge`

Is that correct?

**Comment by fehiepsi** [comment] 2022-03-07 03:28
Did you update jaxlib for the fix? I'm not sure what to do if this is jaxlib problem. You might want to downgrade it if needed I guess.

**Comment by justinrporter** [comment] 2022-03-07 17:10
This is in a docker image, so I built it from scratch. The version of jaxlib I get is `jaxlib                    0.3.0            py39h3498573_2    conda-forge`... Is that correct?

**Comment by fehiepsi** [comment] 2022-03-07 17:48
I think you need to update jaxlib version (or in case the latest version is not available in your system, please consider downgrade jax/jaxlib to older versions). The link https://anaconda.org/conda-forge/jaxlib/files shows the latest version is jaxlib-0.3.0-...-_3

**Comment by justinrporter** [comment] 2022-03-07 19:52
Word.  I'll see if I can manually tell anaconda to use `_3` instead of `_2`. Do you know why anaconda prefers to install `_2` when `_3` is available? Perhaps there is some conflict somewhere? So far my attempts to convince anaconda to install `_3` have failed.

**Comment by fehiepsi** [comment] 2022-03-09 02:26
> Do you know why anaconda prefers to install _2 when _3 is available?

I'm not sure. I just tested in my system and it installed _3 version. Probably the new version is not available to your system.

**Comment by justinrporter** [comment] 2022-03-09 15:43
Good news! For I re-re-rebuilt the docker image today and for some reason it got `_3` instead of `_2`... maybe there was some caching happening somewhere that's now been invalidated?

In any case, I think we can mark this as resolved.

**Closed** 2022-03-09 16:04 UTC
Labels: question
