### ISSUE TITLE
NUTS sometimes does not converge on a regression model

### ISSUE THREAD

**Issue by rusty-robin** [pyro-ppl/numpyro#1360] opened 2022-03-11 09:15 UTC
I observed that NUTS sometimes does not converge on this model (depending on the rng seed). For instance, if I change the seed to 7227991, it converges. Overall it fails to converge about 2-3 times out of 10. I am guessing that its not choosing the initial point properly for sigma/w sometimes and hence the chain diverges? 

The model seems to work fine with Stan though, i.e. converges and gives correct results.

Is this expected? 

```Python
import jax.random
import numpyro
import numpy as np
import numpyro.distributions as dist

from numpyro.infer import MCMC


numpyro.set_platform("cpu")
numpyro.set_host_device_count(4)
import os
import random
import sys


data = dict()
data['x'] =np.array([0.0970,2.1020,0.5840,1.0394,3.4375,1.3102,1.2863,4.5382,1.2539,2.9319,4.7777,4.5937,4.0403,0.7749,1.8342,1.5008,3.9557,1.6095,0.5602,4.7997,1.6436,4.5236,1.9404,1.1508,3.1447,3.3551,0.2669,3.2483,2.5293,0.1596,2.8992,2.5016,4.7589,2.5648,1.9871,0.3201,4.4863,0.5675,0.8897,0.5689,0.5621,0.5701,0.7998,0.3166,4.8490,2.7849,2.6858,4.2393,1.4939,1.7230,0.4202,0.3591,2.5912,3.9753,3.5417,0.3198,2.7192,1.9892,1.9525,4.7293,1.7719,3.7889,2.3613,4.6994,2.0155,3.8840,0.8289,2.1164,1.3342,1.4850,0.5512,0.3919,2.4001,3.1949,4.9759,1.4158,0.6088,2.1599,0.3643,0.6800,2.4031,1.7706,3.7669,4.1080,4.9707,1.9139,4.7615,3.3075,3.6872,4.0946,0.3447,2.7292,0.2768,3.7641,3.3987,0.1833,4.9353,1.9730,2.2034,2.8598])
data['y'] =np.array([4.9404,45.0399,14.6792,23.7890,71.7504,29.2036,28.7251,93.7642,28.0774,61.6389,98.5535,94.8738,83.8054,18.4976,39.6836,33.0162,82.1149,35.1902,14.2033,98.9948,35.8724,93.4728,41.8081,26.0160,65.8950,70.1028,8.3385,67.9659,53.5864,6.1922,60.9839,53.0324,98.1783,54.2960,42.7421,9.4019,92.7252,14.3490,20.7931,14.3781,14.2424,14.4019,18.9951,9.3322,99.9797,58.6983,56.7166,87.7854,32.8781,37.4594,11.4034,10.1829,54.8241,82.5061,73.8340,9.3964,57.3845,42.7835,42.0501,97.5864,38.4374,78.7779,50.2264,96.9873,43.3109,80.6796,19.5773,45.3275,29.6839,32.6994,14.0248,10.8371,51.0026,66.8986,102.5188,31.3158,15.1756,46.1974,10.2855,16.6008,51.0629,38.4128,78.3385,85.1597,102.4138,41.2770,98.2303,69.1497,76.7434,84.8919,9.8933,57.5845,8.5367,78.2816,70.9734,6.6665,101.7066,42.4600,47.0682,60.1959])

def model():
    w=numpyro.sample("w", dist.Exponential(87.2889404296875))
    b=numpyro.sample("b", dist.Normal(1,1))
    sigma=numpyro.sample("sigma", dist.Chi2(31.628190994262695))
    with numpyro.plate("size", np.size(data['y'])):
        numpyro.sample("obs55", dist.Normal(w*data['x']+b,sigma), obs=data['y'])
        

mcmc = MCMC(numpyro.infer.NUTS(model),num_samples=1000,num_warmup=1000,num_chains=4)
mcmc.run(jax.random.PRNGKey(323728029))
mcmc.print_summary()
```

Output:
```
                mean       std    median      5.0%     95.0%     n_eff     r_hat
         b      2.75      0.89      3.00      0.98      4.05   1438.28      1.01
     sigma     39.80     23.18     51.43      0.00     56.96      2.03      8.17
         w      5.01      8.66      0.01      0.00     20.00      2.00    890.88
```

Environment:
```
Python 3.7
Numpyro 0.9.0
Ubuntu 18.04
```

Stan output:
```

                 Mean     MCSE  StdDev        5%       50%    95%    N_Eff  N_Eff/s    R_hat
lp__             -424  2.8e-02     1.2  -4.3e+02  -4.2e+02   -422  2.0e+03  1.4e+04  1.0e+00
w               0.012  2.1e-04   0.013   6.2e-04   8.4e-03  0.038  3.9e+03  2.7e+04  1.0e+00
b                 2.7  2.0e-02     1.0   9.6e-01   2.6e+00    4.3  2.5e+03  1.7e+04  1.0e+00
sigma              53  6.8e-02     3.4   4.8e+01   5.3e+01     59  2.6e+03  1.8e+04  1.0e+00

```

Please let me know if these reports are useful. I am testing numpyro against various models to check for bugs. Since i am new to numpyro, some of these observations maybe already be known (i.e., not a bug) to developers.

**Comment by fehiepsi** [comment] 2022-03-11 15:05
Could you try adding `numpyro.enable_x64()` to the top of your program? Or try `NUTS(..., init_strategy=numpyro.infer.init_to_sample)`.

**Comment by tcbegley** [comment] 2022-03-11 15:07
The problem is with the specification of your model rather than NumPyro. Eyeballing the data it looks like there is very strong signal and very little noise

<img width="300" alt="image" src="https://user-images.githubusercontent.com/15220906/157891849-12069de2-4f11-4288-ae6b-39769c98d09d.png">

I estimate the true values of `w` and `b` that you used to generate the data were 20 and 3 respectively.

Your prior on `w` however (`dist.Exponential(87.2889404296875)`) seems like a poor choice. First of all it can only take positive values (is this intended)? This is equivalent to you assuming that it is _impossible_ that `x` and `y` are negatively correlated. Is that an assumption you truly wish to make?

The bigger problem is that with such a large rate parameter, the exponential distribution is extremely concentrated near 0. This means your attaching infinitessimal prior probability to the true value of twenty. According to your prior you think it's overwhelmingly likely the true value of `w` is in the range 0 - 0.1. Several orders of magnitude smaller than the true value.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/15220906/157892436-dbd25b66-e579-491c-94c9-3ad4599e7361.png">

Running the model with different seeds leads to R hat statistics close to 1, but the model is not doing the right thing. In fact your R hat is one because all chains are stuck at 0 (where all the prior probability is) and can't make the jump to 20 (where the likelihood is large). Seems from the Stan output that the same is happening there, all chains are getting stuck in the same place rather than converging to the right answer, so the R hat of one is misleading you. The NumPyro summary you posted shows an average `w` of 5, which is because one chain makes it to 20, the other three get stuck at 0.

You can get a lot more help with modelling questions on the [Pyro forum](https://forum.pyro.ai/).

**Comment by rusty-robin** [comment] 2022-03-11 17:37
Yes, I agree that the model here has a very constrained prior. So I don't expect the results to be correct, i.e., `20` and `3` for `w` and `b`. However, I just wanted to test the behavior of the NUTS sampler with different kinds of priors. In this case I was expecting that it would converge like stan and produce a large sigma instead, which maybe desirable in some cases.
I also tried with `numpyro.enable_x64()` but i get same results. 

My aim here is to check if this behavior is expected or if its a bug. But if you guys think this behavior is expected, we can close this issue.

**Comment by rusty-robin** [comment] 2022-03-12 06:20
Ok, I obtained the potential energies:

Code:
```python
...
mcmc.run(jax.random.PRNGKey(323728029), extra_fields=("potential_energy",) )
params = mcmc.get_samples(group_by_chain=True)
poten=mcmc.get_extra_fields()["potential_energy"]
print("Chain 0", np.max(poten[:1000]), np.min(poten[:1000]))
print("Chain 1", np.max(poten[1000:2000]), np.min(poten[1000:2000]))
print("Chain 2", np.max(poten[2000:3000]), np.min(poten[2000:3000]))
print("Chain 3", np.max(poten[3000:4000]), np.min(poten[3000:4000]))
```

Output:
```
                mean       std    median      5.0%     95.0%     n_eff     r_hat
         b      2.75      0.89      3.00      0.98      4.05   1438.28      1.01
     sigma     39.80     23.18     51.43      0.00     56.96      2.03      8.17
         w      5.01      8.66      0.01      0.00     20.00      2.00    890.88

Number of divergences: 1
Chain 0: 557.2424 548.98145
Chain 1: 557.612 548.97815
Chain 2: 1294.9126 1288.3512
Chain 3: 559.49304 548.9927
```

Looks like one chain diverges. The potential energy is higher for that chain -- which should not happen ideally? Assuming I am interpreting this correctly.

**Comment by fehiepsi** [comment] 2022-03-12 07:57
Yes, the chain with w~20 seems to be the bad one. Did you add `enable_x64()` at the top of your program or in the middle? I can't think of a reason for why that chain stuck at bad values beside numerical issues (probably our implementation of Exponential does not have a good precision at extreme values).

**Comment by rusty-robin** [comment] 2022-03-12 08:17
Yes, i did enable x64 at the top, but that did not change the behavior. I am just running the program from command line using my conda environment.

I was checking the exponential distribution implementation. It seems its logprob function returns a positive result for negative values instead of nan/inf (like scipy). Is that expected?
I see that there are constraints on the input value. Does that only work during inference? And not when i just use the distribution by itself?

**Comment by fehiepsi** [comment] 2022-03-12 13:55
It is expected. You can enable validation to get -inf for out of support values. But I think it is not the issue here because the domain of w is positive. I tried 30 seeds with x64 but all of them give reasonable results. Could you let me know which seed is failing in x64?

**Comment by rusty-robin** [comment] 2022-03-12 17:49
Try: 2262058 or 901576

**Comment by fehiepsi** [comment] 2022-03-12 20:55
I can confirm that with those seeds, MCMC is not mixing. I looked at the bad chain
```
mcmc.warmup(jax.random.PRNGKey(2262058), collect_warmup=True, extra_fields=("potential_energy",))
mcmc.get_samples(group_by_chain=True)["w"]
```
and saw that `w` is initialized by a value ~7, then gradually move to 20. I can get away from the issue with
```
NUTS(model, init_strategy=numpyro.infer.init_to_sample)
```
The potential energies of such chain are
```
mcmc.get_extra_fields(group_by_chain=True)["potential_energy"][1]
```
```
DeviceArray([513914.42012222, 513914.42012222, 513914.42012222,
             513914.42012222,  98393.27948753,   4330.33481392,
               2293.18986211,   1998.03136204,   1937.28190636, ...
```

It seems that the posterior is multimodal.

**Comment by rusty-robin** [comment] 2022-03-12 21:07
I see. But this wont always work, right? For instance, this initialization strategy may not work if the prior is closer to the second mode? 

Also, do you have any insight on how stan avoids this problem? Better initialization method?

On a different note, I am also observing some issues with multiple linear regression models: numpyro converges to wrong results (stan is correct). Should i post one of those here or create a separate issue?

**Comment by fehiepsi** [comment] 2022-03-12 21:41
>  how stan avoids this problem? Better initialization method?

I don't know. I guess so. Stan might generate a collection of init values and choose the best one to start with.

I'm not sure what would be a reasonable initialization strategy. In the above model, chains are not mixing and to me, it could be a good signal to explore more, rather than ignore (which might omit areas that has small probability). Typically, I rarely use strong priors and will try to scale it to unit scale: e.g. `w = numpyro.sample("w_base", dist.Exponential(1)) / 87.2889404296875`.

**Comment by martinjankowiak** [comment] 2022-03-12 21:46
it's always possible that there exist better and more robust initialization strategies but i think it's always good to remember andrew gelman's [folk theorem](https://statmodeling.stat.columbia.edu/2008/05/13/the_folk_theore/)

**Comment by rusty-robin** [comment] 2022-03-12 21:58
Here is another example of a multiple linear regression model. Here, the model converges, but the results are quite different than stan. Also the predictive accuracy is not that great in this case. I also tried different initialization strategies, but that did not affect the results much. However, if I change, Laplace to Normal, the results are better (better predictive accuracy).

```python
import jax.random
import jax.numpy as jnp
import numpyro
import numpy as np
import numpyro.distributions as dist
from numpyro.infer import MCMC, NUTS, HMC, Predictive
from numpyro.diagnostics import effective_sample_size, split_gelman_rubin
numpyro.set_platform("cpu")
numpyro.set_host_device_count(4)
numpyro.enable_x64()
import os
import random
import sys
curpath=os.path.dirname(os.path.abspath(sys.argv[0]))
random.seed(1086133844)
np.random.seed(1040525466)

data = dict()
data['x'] =np.array([[0.3127,0.7185,0.9494,0.5597,0.7358,0.1210,0.6191,0.5667,0.4503,0.5986],[0.0269,0.7518,0.9182,0.6499,0.4869,0.3073,0.8153,0.6999,0.0878,0.1670],[0.7447,0.5607,0.0876,0.7848,0.5527,0.6284,0.2125,0.6352,0.8686,0.7983],[0.1576,0.0972,0.6508,0.7716,0.6274,0.1363,0.7613,0.2494,0.3428,0.9261],[0.7717,0.4577,0.0172,0.8652,0.8721,0.1606,0.9938,0.0563,0.5016,0.5695],[0.1718,0.2058,0.9203,0.6626,0.5851,0.1158,0.4355,0.0705,0.7436,0.2993],[0.3664,0.5945,0.0679,0.5061,0.9727,0.2606,0.8866,0.7922,0.8299,0.4857],[0.1521,0.6116,0.8895,0.8145,0.8965,0.3734,0.5860,0.2676,0.9310,0.6909],[0.6845,0.6834,0.3010,0.4828,0.8348,0.3919,0.4748,0.6864,0.1595,0.2750],[0.1263,0.8909,0.6362,0.1842,0.4666,0.9637,0.3681,0.4188,0.3020,0.7719]])
data['weight'] =np.array([3.9238,3.1421,6.5905,2.8718,1.7819,1.4975,0.1834,7.6811,5.0964,2.7595])
data['y'] =np.array([53.1548,81.4405,79.8570,90.5019,95.7489,55.4778,74.3114,64.2782,76.5626,82.0193])

def model():
    w_param_1=numpyro.sample("w_param_1", dist.Gamma(15.13160514831543,11.33822250366211))
    w=numpyro.sample("w", dist.Normal(1.0*np.ones([10]),w_param_1*np.ones([10])))
    b=numpyro.sample("b", dist.Normal(1.0,10.0))
    with numpyro.plate("size", np.size(data['y'])):
        numpyro.sample("obs77", dist.Laplace(jnp.matmul(data['x'],w)+b,1.0), obs=data['y'])
        


mcmc = MCMC(numpyro.infer.NUTS(model,step_size=1.0,adapt_step_size=True,adapt_mass_matrix=True,target_accept_prob=0.8,max_tree_depth=10,find_heuristic_step_size=False),num_samples=1000,num_warmup=1000,num_chains=4)
mcmc.run(jax.random.PRNGKey(1670940923))
params = mcmc.get_samples(group_by_chain=True)
mcmc.print_summary()

realy=data['y']
data['y']=None
pred=Predictive(model, posterior_samples=mcmc.get_samples())
ypred=pred(jax.random.PRNGKey(1670940923))["obs77"].mean(0)
print("diff", np.abs(ypred-realy))
```

Output:
```
                 mean       std    median      5.0%     95.0%     n_eff     r_hat
          b     54.12      5.83     54.27     45.10     64.13   1543.76      1.00
       w[0]      6.73      3.92      6.77      0.14     12.90   1488.66      1.00
       w[1]     -0.28      4.69     -0.40     -7.79      7.43   1400.32      1.00
       w[2]     -9.72      3.29     -9.72    -14.97     -4.29   1446.26      1.00
       w[3]     15.77      4.43     15.79      8.19     22.95   1423.64      1.00
       w[4]     -6.72      4.39     -6.89    -13.86      0.74   2128.27      1.00
       w[5]     17.22      4.81     17.00      9.43     25.05   1348.68      1.00
       w[6]     23.77      4.18     23.88     17.46     30.97   1158.96      1.00
       w[7]     -0.07      3.10     -0.14     -4.98      5.16   1824.89      1.00
       w[8]    -19.15      3.07    -19.37    -23.83    -13.93   1217.37      1.00
       w[9]     16.74      3.77     16.94     10.38     22.79   1674.39      1.00
  w_param_1      5.77      0.60      5.77      4.76      6.75   1360.44      1.00

Number of divergences: 0
diff [15.67533691  3.57009744  0.52349641  4.37040016  2.64930936  0.39438193
  0.6493642   2.93737136  0.56254751  1.25814957]              
```


Stan output:
```                    Mean     MCSE   StdDev        5%       50%       95%    N_Eff  N_Eff/s    R_hat
lp__            -1.0e+02  1.1e-01  3.3e+00  -1.1e+02  -1.0e+02  -9.9e+01  9.0e+02  2.0e+02  1.0e+00
accept_stat__    7.8e-01  4.2e-03  1.8e-01   4.2e-01   8.3e-01   9.9e-01  1.8e+03  4.0e+02  1.0e+00
stepsize__       6.6e-03  7.8e-04  1.1e-03   4.8e-03   7.5e-03   7.5e-03  2.0e+00  4.4e-01  1.7e+14
treedepth__      8.6e+00  1.6e-01  7.5e-01   7.0e+00   9.0e+00   1.0e+01  2.3e+01  4.9e+00  1.1e+00
n_leapfrog__     5.7e+02  4.8e+01  2.8e+02   2.6e+02   5.1e+02   1.0e+03  3.5e+01  7.7e+00  1.0e+00
divergent__      0.0e+00     -nan  0.0e+00   0.0e+00   0.0e+00   0.0e+00     -nan     -nan     -nan
energy__         1.1e+02  1.4e-01  4.2e+00   1.0e+02   1.1e+02   1.2e+02  8.9e+02  1.9e+02  1.0e+00
w[1]             1.6e+01  3.9e-01  8.5e+00   2.0e+00   1.6e+01   3.0e+01  4.7e+02  1.0e+02  1.0e+00
w[2]            -3.7e+01  3.5e-01  8.4e+00  -5.1e+01  -3.7e+01  -2.3e+01  5.6e+02  1.2e+02  1.0e+00
w[3]            -3.3e-01  3.0e-01  6.7e+00  -1.1e+01  -2.7e-01   1.1e+01  4.8e+02  1.0e+02  1.0e+00
w[4]             2.6e+01  2.1e-01  5.4e+00   1.8e+01   2.6e+01   3.5e+01  7.0e+02  1.5e+02  1.0e+00
w[5]            -3.4e+00  2.0e-01  5.3e+00  -1.2e+01  -3.6e+00   5.9e+00  7.3e+02  1.6e+02  1.0e+00
w[6]             6.6e+01  3.8e-01  9.2e+00   5.0e+01   6.6e+01   8.1e+01  5.8e+02  1.3e+02  1.0e+00
w[7]             5.0e+01  3.6e-01  8.0e+00   3.7e+01   5.0e+01   6.3e+01  4.8e+02  1.0e+02  1.0e+00
w[8]             7.6e+00  1.4e-01  3.6e+00   1.7e+00   7.5e+00   1.4e+01  6.8e+02  1.5e+02  1.0e+00
w[9]            -2.1e+01  1.3e-01  3.4e+00  -2.6e+01  -2.1e+01  -1.5e+01  6.4e+02  1.4e+02  1.0e+00
w[10]            2.8e+00  1.1e-01  3.4e+00  -2.3e+00   2.4e+00   8.9e+00  9.7e+02  2.1e+02  1.0e+00
b                2.9e+01  3.9e-01  9.4e+00   1.3e+01   2.9e+01   4.4e+01  5.8e+02  1.3e+02  1.0e+00
w_param_1        2.0e+01  1.3e-01  4.0e+00   1.5e+01   2.0e+01   2.8e+01  9.9e+02  2.1e+02  1.0e+00
```

**Comment by fehiepsi** [comment] 2022-03-13 03:21
Could you print out the last sample from Stan chain so I can help you compare two log densities? I tried
```
from numpyro.infer.util import log_density
stan_values = {"w": np.array([16., -37., -0.33, 26., -3.4, 66., 50., 7.6, -21., 2.8]), "b": 29., "w_param_1": 20.}
log_density(numpyro.handlers.substitute(model, data=stan_values), (), {}, {})[0]
```
but it does not give good result (compare to `mcmc.last_state.potential_energy`)

Regarding predictive, I think it does not tell much story unless you use improper priors.

**Comment by rusty-robin** [comment] 2022-03-13 03:30
These are the values from the last few rows:

```CSV
lp__,w.1,w.2,w.3,w.4,w.5,w.6,w.7,w.8,w.9,w.10,b,w_param_1
-106.338,14.1794,-35.7157,-3.49977,24.6109,-7.2649,63.9874,50.4802,11.7895,-16.4595,3.16958,30.1657,17.5478
-102.66,17.3281,-34.6901,0.394097,25.6135,-7.53056,64.2051,52.1386,10.4112,-18.6184,3.15572,26.366,17.1373
-103.868,26.7976,-44.627,8.11671,27.7954,-6.06165,76.0467,57.273,9.1238,-19.696,3.18572,15.6788,20.8359
-106.995,24.9881,-39.783,4.42986,28.8461,-10.081,66.0369,59.6957,10.8237,-17.0186,2.28201,18.065,22.931
```

**Comment by rusty-robin** [comment] 2022-03-13 03:38
Actually, scratch that. I realized I was using Gamma instead of InverseGamma in NumPyro which was causing the difference in results! :'( 

Now it works after I make that change! Sorry about the fuss. :/

**Comment by fehiepsi** [comment] 2022-03-13 03:49
Glad that you figured it out! I guess we can close this issue? Just a comment that it is better to reparam your model
```
w=numpyro.sample("w_base", dist.Normal(1.0*np.ones([10]),np.ones([10]))) * w_param_1
```

**Closed by fehiepsi** 2022-03-13 03:49 UTC
Labels: discussion

**Comment by rusty-robin** [comment] 2022-03-13 03:52
Thanks for the help @fehiepsi! 

> Just a comment that it is better to reparam your model

Thanks. Will keep that in mind.

Just another thing. Is there a good documentation on all the debugging tools/apis that you mentioned on this thread: logdensity, potential energy, plotting the posterior, etc?

**Comment by fehiepsi** [comment] 2022-03-13 11:36
We don't have it yet. Maybe we can add a Tips and tricks notebook. Do you want to start with some that you think important?
